package constants

// 日志模板集中管理。业务字段变更时必须同步修改对应模板与调用处。
const (
	LogServerStarted        = "server started on :%s env=%s"
	LogServerShutdown       = "server shutdown, err=%v"
	LogDBConnected          = "database connected host=%s db=%s"
	LogRedisConnected       = "redis connected host=%s"
	LogMigrateCompleted     = "database auto migrate completed, tables=%d"
	LogSeedCompleted        = "seed data completed, users=%d owners=%d products=%d bins=%d"
	LogRequestIn            = "request in method=%s path=%s request_id=%s"
	LogRequestOut           = "request out method=%s path=%s status=%d latency_ms=%d request_id=%s"
	LogPanicRecovered       = "panic recovered path=%s request_id=%s err=%v"
	LogLoginSuccess         = "user login success username=%s role=%s"
	LogLoginFailed          = "user login failed username=%s reason=%s"
	LogRegisterUser         = "user registered username=%s role=%s"
	LogCreateOwner          = "owner created owner_id=%d name=%s operator=%s role=%s"
	LogUpdateOwner          = "owner updated owner_id=%d name=%s operator=%s role=%s"
	LogAdjustOwnerCredit    = "owner credit adjusted owner_id=%d credit_limit=%v operator=%s role=%s"
	LogSuspendOwner         = "owner suspended owner_id=%d operator=%s role=%s"
	LogActivateOwner        = "owner activated owner_id=%d operator=%s role=%s"
	LogCreateProduct        = "product created product_id=%d sku=%s owner_id=%d operator=%s role=%s"
	LogUpdateProduct        = "product updated product_id=%d sku=%s operator=%s role=%s"
	LogCreateInbound        = "inbound created order_no=%s owner_id=%d operator=%s role=%s"
	LogReceiveInbound       = "inbound received order_no=%s operator=%s role=%s"
	LogQCInbound            = "inbound qc completed order_no=%s operator=%s role=%s"
	LogShelveInbound        = "inbound shelved order_no=%s operator=%s role=%s"
	LogCompleteInbound      = "inbound completed order_no=%s operator=%s role=%s"
	LogCreateOutbound       = "outbound created order_no=%s owner_id=%d operator=%s role=%s"
	LogPickOutbound         = "outbound picked order_no=%s operator=%s role=%s"
	LogCheckOutbound        = "outbound checked order_no=%s operator=%s role=%s"
	LogPackOutbound         = "outbound packed order_no=%s operator=%s role=%s"
	LogShipOutbound         = "outbound shipped order_no=%s tracking_no=%s operator=%s role=%s"
	LogCompleteOutbound     = "outbound completed order_no=%s operator=%s role=%s"
	LogCreateBin            = "bin created bin_id=%d area=%s rack=%s operator=%s role=%s"
	LogBatchCreateBin       = "bin batch created count=%d operator=%s role=%s"
	LogUpdateBin            = "bin updated bin_id=%d operator=%s role=%s"
	LogAuditRecord          = "audit recorded module=%s action=%s entity_type=%s entity_id=%s operator=%s role=%s"
	LogRecommendBin         = "bin recommended product_id=%d bin_id=%d quantity=%d operator=%s role=%s"
	LogDashboardLoaded      = "dashboard summary loaded owner_id=%d operator=%s role=%s"
	LogInsufficientStock    = "insufficient stock product_id=%d bin_id=%d required=%d available=%d order_no=%s"
)
